### ISSUE TITLE
Does not work on Android 2.2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [turbomanage/basic-http-client#8]
```
CookieManager is only available from Gingerbread. See pre 2.3 devices throw 
exceptions:

09-21 17:46:51.916: E/AndroidRuntime(3439): Caused by: 
java.lang.NoClassDefFoundError: java.net.CookieManager
09-21 17:46:51.916: E/AndroidRuntime(3439):     at 
com.turbomanage.httpclient.AbstractHttpClient.ensureCookieManager(AbstractHttpCl
ient.java:437)
09-21 17:46:51.916: E/AndroidRuntime(3439):     at 
com.turbomanage.httpclient.AbstractHttpClient.<clinit>(AbstractHttpClient.java:2
7)

Is it possible to workaround it?
```

Original issue reported on code.google.com by `versluyssander` on 21 Sep 2012 at 3:56
- Merged into: #7
